name: Aquarius-Protocol

on:
  push:
    branches: [arbitrum]
  pull_request:
    branches: [arbitrum]

jobs:
  test:
    name: Arbitrum branch test
    runs-on: self-hosted
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: arbitrum
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install Dependencies
      run: |
        sudo wget https://github.com/ethereum/solidity/releases/download/v0.5.16/solc-static-linux -O /usr/local/bin/solc
        sudo chmod +x /usr/local/bin/solc
        sudo apt install make g++ -y
    - run: npm install -g yarn
    - run: yarn --frozen-lockfile
    - name: yarn lint and test
      run: |
        yarn run lint --if-present
        yarn run test --if-present
